spring:
  datasource:
    username: root
    password: zsq662663
    url: jdbc:mysql://localhost:3306/apple?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      enabled: true
      max-request-size: 1GB
      max-file-size: 1GB
      file-size-threshold: 30MB
  mail:
    host: smtp.qq.com
    username: 2231925844@qq.com
    password: waqyfpldmprvdjjj
    protocol: smtp
    properties.mail.smtp.ssl.enable: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    default-encoding: utf-8

mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.coco.model

#  spring.mail.properties.mail.smtp.starttls.enable=true
#  spring.mail.properties.mail.smtp.starttls.required=true
#  spring.mail.default-encoding=UTF-8
#  ————————————————
#  版权声明：本文为CSDN博主「墨9」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
#  原文链接：https://blog.csdn.net/m0_37732829/article/details/90637922